services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: revali_mssql
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    env_file:
      - .env
    volumes:
      - ./sql-scripts:/scripts:ro
    entrypoint: /bin/bash
    command:
      - -c
      - |
        until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "$MSSQL_SA_PASSWORD" -Q 'SELECT 1' 2>/dev/null; do
          echo 'Wachten op SQL Server...';
          sleep 2;
        done;
        echo 'SQL Server is online, running init script...';
        /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "$MSSQL_SA_PASSWORD" -i /scripts/mssql_init.sql;
        echo 'Init finished.'